name: Publish @microsoft/tiktokenizer to npmjs

on: workflow_dispatch
    
defaults:
  run:
    working-directory: tokenizer_ts
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org'
          scope: '@microsoft'
          always-auth: true
      - run: npm ci
      - run: npm run build
      - run: npm run test
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: npm-package
          path: tokenizer_ts/*.tgz
