name: PR build

on:
  pull_request:
    branches: [ main ]
    
defaults:
  run:
    working-directory: tokenizer_ts
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: bikutadesu/create-npmrc@v1.0.0
        with:
          org_name: Microsoft
          auth_token: ${{ secrets.GITHUB_TOKEN }}
          always_auth: true
      - run: npm ci
      - run: npm run build
      - run: npm run test
